### ISSUE TITLE
Install and configure custom version of postgesql

### ISSUE THREAD

**Issue by Polichronucci** [debops/ansible-postgresql_server#13]
In order to install an upstream version of postgresql it is needed to do 3 things.
Set variables: (ex with version 9.3)

    postgresql_server__upstream: True
    postgresql_server__base_packages: [ 'postgresql-9.3', 'postgresql-client-9.3', 'postgresql-contrib-9.3', 'python-psycopg2' ]

And then you have to set a variable with the --extra-vars console parameter:

    postgresql_server__version: '9.3'

This last variable is the most annoying one because you cant set it somewhere static but instead have to include it each time the postgresql_server role is run.

I thought of something like this in the tasks/main.yml file:

    31    - name: Set default PostgreSQL version variable                                 
    32      set_fact:                                                                     
    33        postgresql_server__version: '{{ ansible_local.postgresql.version            
    34                                         if (ansible_local|d() and ansible_local.postgresql|d() and
    35                                             ansible_local.postgresql.version|d())  
    +                                          postgresql_server__version_custom
    +                                          elif (postgresql_server__version_custom)
    36                                         else postgresql_server__register_version.stdout }}'
    37      tags: [ 'role::postgresql_server:packages', 'role::postgresql_server:config', 
    38              'role::postgresql_server:auto_backup' ] 

But this wont work since jinja doesn't support more than a single conditional this way.
What do you think?

It would be great if we could figure out a way to eliminate the need for the "postgresql_server__base_packages" variable assignment. So just by defining the "postgresql_server__version_custom" variable the role will figure out the right packages.

**Comment by drybjed** [comment]
The thing is, `postgresql_server__version` (and its counterpart in the `debops.postgresql` role aren't meant to specify what version of the database you want installed. They are used to "pin" the currently preferred PostgreSQL version, which is defined via APT preferences - you can see that by checking `apt-get policy postgresql`. Version "pinning" is important, because many of the tasks use the version number in the file paths, for example:
```
/etc/postgresql/9.4/main/postgresql.conf
/var/lib/postgresql/9.4/main/
```
That's why the `postgresql_server__version` exists.

I admit that currently there's no easy way to install a specific PostgreSQL version other than the currently preferred one. Furthermore, role doesn't really support managing multiple PostgreSQL versions on the same host, or upgrading from one version to another - things might break unexpectedly if you do that. My solution for these cases at the moment is just to install new PostgreSQL on a different host / LXC container and move the database. After all, configuration of new hosts takes mere minutes now, and you don't need to do this manually.

Setting custom `postgresql_server__base_packages` to install a different PostgreSQL version than the one selected by the `postgresql` metapackage is a valid way to change the role behaviour. You just need to do that in the inventory. Many other DebOps roles are designed to be modified that way. One problem at the moment is that if you install older version of PostgreSQL rather than the one preferred by APT, without changing the preference, the role will pick the wrong PostgreSQL version to use. So adding a variable in the `set_fact` condition if necessary is a good idea, I think. Although, I would call the variable `postgresql_server__preferred_version` and set it as empty by default - user would set it if she wants to install a different PG version than the one chosen automatically. I'll try see if that works as expected.

**Comment by drybjed** [comment]
Looks like adding a variable to specify preferred version in addition to APT packages works as expected. I'll add that in both roles and include some documentation about how to use different PostgreSQL versions.

**Comment by Polichronucci** [comment]
Nice :dancers:

**Comment by drybjed** [comment]
@Polichronucci Both roles have been updated, check if this works for you.

**Comment by Polichronucci** [comment]
@drybjed Yep this seems to do the trick.

**Comment by drybjed** [comment]
Great, so I'm clossing this issue then.
