### ISSUE TITLE
Task "Create PostgreSQL clusters" fails if locale is not available

### ISSUE THREAD

**Issue by mundus08** [debops/ansible-postgresql_server#34]
Playbook:
    postgresql_server__locale: 'de_DE.UTF-8'

Error:
"stderr_lines": ["initdb: invalid locale name \"de_DE.UTF-8\

Cluster creation works if locale is generated before:
  modify /etc/locale.gen  
  locale-gen && update-locale

OS: Debian 9

**Comment by drybjed** [comment]
I can confirm this as an issue as well on Debian 8. This happens with locales are not configured on a host. In DebOps, at the moment this is done by the [`debops.console` role](https://github.com/debops/ansible-console/) but the related tasks would probably need to be moved to a separate Ansible role. After that, roles like `debops.postgresql_server` could use it as a dependency.

I'm closing this issue so that it doesn't block the merge of DebOps roles into unified `git` repository. I'll get back to it after that.
